name: env_name
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.11.0
  - jupyter=1.0.0
  - matplotlib=3.8.0
  - notebook=7.0.6
  - numpy=1.26.3
  - seaborn=0.13.2
  - pip=23.3.2
  - python=3.11.7
  - python-dotenv=0.21.0